export const COLORS = {
  brand: '#f97316',
  brandLight: '#fb923c',
  accent: '#f97316',
  success: '#22c55e',
  warning: '#ef4444',
} as const;

const RAW_PAKISTAN_CITIES = [
  'Abbottabad',
  'Ahmadpur East',
  'Ali Pur',
  'Arifwala',
  'Attock',
  'Badin',
  'Bahawalnagar',
  'Bahawalpur',
  'Bannu',
  'Batkhela',
  'Bhakkar',
  'Bhimber',
  'Burewala',
  'Chakwal',
  'Chaman',
  'Charsadda',
  'Chiniot',
  'Chishtian',
  'Dadu',
  'Daska',
  'Dera Allah Yar',
  'Dera Ghazi Khan',
  'Dera Ismail Khan',
  'Faisalabad',
  'Fort Abbas',
  'Ghotki',
  'Gilgit',
  'Gojra',
  'Gujar Khan',
  'Gujranwala',
  'Gujrat',
  'Gwadar',
  'Hafizabad',
  'Haripur',
  'Haroonabad',
  'Hasilpur',
  'Hub',
  'Hunza',
  'Hyderabad',
  'Islamabad',
  'Jacobabad',
  'Jaranwala',
  'Jhang',
  'Jhelum',
  'Khairpur',
  'Khairpur Tamewali',
  'Khanewal',
  'Khanpur',
  'Kharian',
  'Khuzdar',
  'Kohat',
  'Karachi',
  'Kasur',
  'Kot Addu',
  'Kotli',
  'Lahore',
  'Larkana',
  'Layyah',
  'Lodhran',
  'Mailsi',
  'Mandi Bahauddin',
  'Mansehra',
  'Mardan',
  'Mianwali',
  'Minchinabad',
  'Mirpur',
  'Mirpur Khas',
  'Mingora',
  'Multan',
  'Murree',
  'Muzaffarabad',
  'Muzaffargarh',
  'Nankana Sahib',
  'Narowal',
  'Nawabshah',
  'Nowshera',
  'Okara',
  'Pakpattan',
  'Parachinar',
  'Pasni',
  'Pattoki',
  'Peshawar',
  'Qila Abdullah',
  'Quetta',
  'Rahim Yar Khan',
  'Rawalakot',
  'Rawalpindi',
  'Sadiqabad',
  'Sahiwal',
  'Sanghar',
  'Sargodha',
  'Sehwan',
  'Shakargarh',
  'Sheikhupura',
  'Shikarpur',
  'Sialkot',
  'Skardu',
  'Sukkur',
  'Swabi',
  'Talagang',
  'Tando Adam',
  'Tando Allahyar',
  'Tando Muhammad Khan',
  'Tank',
  'Taxila',
  'Thatta',
  'Toba Tek Singh',
  'Turbat',
  'Umerkot',
  'Vehari',
  'Wah Cantonment',
  'Zafarwal',
  'Zhob',
  'Ziarat',
];

function dedupeCities(cities: string[]): string[] {
  const seen = new Map<string, string>();
  for (const city of cities) {
    const trimmed = city.trim();
    const key = trimmed.toLowerCase();
    if (!key || seen.has(key)) continue;
    seen.set(key, trimmed);
  }
  return [...seen.values()].sort((a, b) => a.localeCompare(b));
}

export const PAKISTAN_CITIES = dedupeCities(RAW_PAKISTAN_CITIES);

export const PAKISTAN_CITY_OPTIONS = PAKISTAN_CITIES.map((city) => ({
  value: city,
  label: city,
}));

export const ORDER_STATUS_COLORS: Record<string, string> = {
  AWAITING_BILTY_CHARGES: 'bg-amber-100 text-amber-800',
  AWAITING_PAYMENT: 'bg-amber-100 text-amber-800',
  PAYMENT_SUBMITTED: 'bg-blue-100 text-blue-800',
  CONFIRMED: 'bg-green-100 text-green-800',
  CANCELLED: 'bg-red-100 text-red-800',
};

export const BOOKING_STATUS_COLORS: Record<string, string> = {
  PENDING: 'bg-amber-100 text-amber-800',
  SCHEDULED: 'bg-green-100 text-green-800',
};
