function formatDate(value: unknown): string {
  if (!value) return '—';
  const d = new Date(String(value));
  if (Number.isNaN(d.getTime())) return String(value).slice(0, 10);
  return d.toLocaleDateString('en-PK', { day: 'numeric', month: 'short', year: 'numeric' });
}

function formatTime(value: unknown): string {
  if (!value) return '—';
  const s = String(value);
  const [h, m] = s.split(':');
  const hour = parseInt(h, 10);
  if (Number.isNaN(hour)) return s;
  const ampm = hour >= 12 ? 'PM' : 'AM';
  const h12 = hour % 12 || 12;
  return `${h12}:${m ?? '00'} ${ampm}`;
}

function esc(value: unknown): string {
  return String(value ?? '—')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function downloadBookingReceipt(receipt: Record<string, unknown>) {
  const branch = (receipt.branch ?? {}) as Record<string, unknown>;
  const customer = (receipt.customer ?? {}) as Record<string, unknown>;
  const service = (receipt.service ?? {}) as Record<string, unknown>;
  const visitDate = receipt.date;
  const visitTime = receipt.confirmedTime ?? receipt.time;
  const hasVisitSchedule = Boolean(visitDate && visitTime);

  const scheduleSection = hasVisitSchedule
    ? `<div class="confirmed-box">
    <div class="label">Scheduled Visit</div>
    <div class="time">${formatTime(visitTime)}</div>
    <div class="date">${formatDate(visitDate)}</div>
    <p class="hint">Please arrive at the branch on this date and time.</p>
  </div>`
    : `<div class="section">
    <h2>Visit Schedule</h2>
    <p>Appointment date and time will be confirmed by the branch.</p>
  </div>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Service Booking Receipt #${esc(receipt.bookingId)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, Helvetica, sans-serif; color: #1a1a1a; padding: 40px; max-width: 720px; margin: 0 auto; }
    h1 { font-size: 22px; color: #0d4f2b; margin-bottom: 4px; }
    .subtitle { font-size: 13px; color: #666; margin-bottom: 28px; }
    .badge { display: inline-block; background: #0d4f2b; color: #fff; padding: 4px 12px; border-radius: 4px; font-size: 12px; font-weight: bold; margin-bottom: 24px; }
    .section { margin-bottom: 20px; }
    .section h2 { font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #888; margin-bottom: 6px; }
    .section p { font-size: 14px; line-height: 1.6; }
    .confirmed-box { background: #f0fdf4; border: 2px solid #0d4f2b; border-radius: 8px; padding: 16px 20px; margin: 24px 0; text-align: center; }
    .confirmed-box .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: #0d4f2b; font-weight: bold; }
    .confirmed-box .time { font-size: 28px; font-weight: bold; color: #0d4f2b; margin: 8px 0 4px; }
    .confirmed-box .date { font-size: 16px; color: #333; font-weight: 600; }
    .confirmed-box .hint { font-size: 12px; color: #555; margin-top: 10px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 12px; color: #666; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>CROWN EV — Service Booking Receipt</h1>
  <p class="subtitle">Booking #${esc(receipt.bookingId)}</p>
  <span class="badge">${esc(receipt.status)}</span>

  <div class="grid">
    <div class="section">
      <h2>Branch</h2>
      <p><strong>${esc(branch.name)}</strong><br/>
      ${esc(branch.location)}<br/>
      ${branch.phone ? `Phone: ${esc(branch.phone)}` : ''}</p>
    </div>
    <div class="section">
      <h2>Customer</h2>
      <p><strong>${esc(customer.name)}</strong><br/>
      ${customer.phone ? `Phone: ${esc(customer.phone)}` : ''}</p>
    </div>
  </div>

  <div class="section">
    <h2>Service</h2>
    <p><strong>${esc(service.name)}</strong>${service.duration ? ` — ${esc(service.duration)} min` : ''}</p>
  </div>

  ${scheduleSection}

  <div class="footer">
    Please show this receipt when you arrive at the branch.<br/>
    Generated by Crown EV Management System.
  </div>
  <script>window.onload = function() { window.print(); };</script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) {
    alert('Please allow pop-ups to download the receipt.');
    return;
  }
  win.document.write(html);
  win.document.close();
}
